#!/usr/bin/env python
import httplib,requests
from bs4 import BeautifulSoup
from pprint import pprint,pformat
from random import randrange
from optparse import OptionParser, OptionGroup
import sys, re

def process_opts():
    usage = """
    Put text into a format yospos can read.

    usage %prog test
    """

    parser = OptionParser(usage=usage)

    (options, args) = parser.parse_args()
    return (options, args)

class SparkleeText(object):

    def __init__(self, **kwargs):
        self.opts = kwargs['opts']
        self.args = kwargs['args']

        self.gliturl = "http://www.sparklee.com/make?text=%(text)s&font=%(font)s&size=50&color=%(font_color)s&bkcolor=%(background_color)s&angle=0"

        self.session = requests.session()
        self.user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.114 Safari/537.36'

    def run(self):
        allchars = []
        for arg in self.args:
            for char in arg:
                if char == ' ':
                    allchars.append(' ')
                else:
                    allchars.append(self.get_sparklee(char))
            allchars.append(' ')

        endstr = ""
        for char in allchars:
            if char == " ":
                endstr = endstr + char
            else:
                endstr = endstr + ("[img]%s[/img]" % char)

        print endstr


    def get_sparklee(self, string, **kwargs):
        interp = {}
        interp['font'] = kwargs.get('font', self._random_font())
        interp['font_color'] = kwargs.get('font_color', self._random_color())
        interp['background_color'] = kwargs.get('background_color', self._random_color())

        try:
            interp['text'] = str(string)
        except ValueError, e:
            print "Could not render %s as ascii: %s" % (string, str(e))
            sys.exit(0)

        target_url = self.gliturl % interp

        resp = self.session.get(target_url, headers={'User-Agent' : self.user_agent})

        if resp.status_code not in [200,301,302]:
            raise Exception("Failed to retrieve url %s" % target_url)

        soup = BeautifulSoup(resp.text)
        yui_main = soup.find(id='yui-main')
        image = yui_main.find('img', {'alt' : 'Glitter Text Generator'})

        return image.attrs['src']



    def _random_color(self):
        return "".join(hex(randrange(256))[2:] for x in range(3))

    def _random_font(self):
        fonts = ["5-cent",
            "action-is",
            "aether-fox",
            "af-pepsi",
            "african",
            "airmole",
            "alaskan-nights",
            "alexis",
            "almonte",
            "almonte-snow",
            "anklepants",
            "army",
            "as-seen-on-TV",
            "astrolyte",
            "atarian",
            "atomic-bomb",
            "av-qest",
            "baby-blocks",
            "babylon-5",
            "bad-cargo",
            "baltar",
            "bamboo",
            "base",
            "batman-forever",
            "battlefield",
            "bauer",
            "baveuse",
            "bazooka",
            "bboy",
            "beach-house-stars-italic",
            "beast-machines",
            "beesknees",
            "betty-noir",
            "beware",
            "billo",
            "black-wolf",
            "blast",
            "bling-ring",
            "block",
            "blood-feast",
            "blood-of-dracula",
            "bloodgutter-99",
            "bloody",
            "bn-machine",
            "boaz-phat",
            "bodidly-bold",
            "bonzai",
            "bootle",
            "borg",
            "borg-9",
            "boyz-r-gross",
            "brass-monkey",
            "bric-a-braque",
            "bring-tha-noize",
            "brooklyn-kid",
            "brrrrr",
            "buffied",
            "bullpen",
            "burn-out",
            "callahan",
            "candy-cane",
            "carbon-black",
            "cat-women",
            "cauldron",
            "celtic-garamond",
            "cheap-sign",
            "chemical-reaction",
            "chippewa-falls",
            "chrispy",
            "chromosome-heavy",
            "clouds-of-despair",
            "clouds-of-hope",
            "college",
            "comic-sans",
            "contour",
            "corpse",
            "corpulent-caps",
            "coverse-allstars",
            "cowboys",
            "crack-babies",
            "cramps",
            "crass",
            "creature",
            "creeper",
            "creepy",
            "creepy-girl",
            "crystal-radio-kit",
            "curlz",
            "da-bomb",
            "dark-side",
            "day-poster-black",
            "dead-alive",
            "deathhead-kelt-caps",
            "debussy",
            "decipher",
            "deftone-stylus",
            "degrassi",
            "demon-night",
            "devils-handshake",
            "die-nasty",
            "digital",
            "diploma",
            "dirty-bakers-dozen",
            "dirty-ego",
            "dirty-headline",
            "disintigration",
            "disney-print",
            "distant-galaxy",
            "distoria",
            "distress",
            "dodger",
            "dokyo",
            "dope-jam",
            "double-feature",
            "dracula",
            "due-date",
            "easily-amused",
            "eastside-motel",
            "edwardian-script",
            "enter-sansman",
            "eraser",
            "eraser-dust",
            "evil-of-frankenstein",
            "fade-to-grey",
            "fanatika-two",
            "fangs",
            "fat-tip",
            "fatboy-slim",
            "fatty-bombatty",
            "fedora",
            "flakes",
            "flashit",
            "fluoride-beings",
            "flying-leatherneck",
            "fontovision",
            "foonky-starred",
            "forte",
            "french-script",
            "friday13",
            "funland-park",
            "futura",
            "futurex-phat",
            "futuri-black",
            "garage-shock",
            "gas-huffer-phat",
            "genotype",
            "ghost-gothic",
            "ghost-town",
            "ghostly",
            "gigi",
            "gilgongo",
            "gloucester",
            "gmaff-shit",
            "gogo-squat",
            "goodbye-cruel-world",
            "gore-font",
            "gourmand-bold",
            "governor",
            "goya",
            "graffiti",
            "graffiti-three",
            "graffiti-treat",
            "gramophone",
            "grand-stylus",
            "grave-digger",
            "graveyard",
            "graveyard-shift",
            "grease",
            "great-lakes",
            "grinched",
            "grunge",
            "grunge-caltek",
            "grunge-rocker",
            "guanine",
            "guinness-extra-stout",
            "gunplay",
            "gyparody",
            "h-man",
            "hackers",
            "halloween",
            "halloween-match",
            "hamburger-heaven",
            "han-solo",
            "hardcore",
            "haunt",
            "hawaiian-punk",
            "hawkeye",
            "headhunter",
            "helldorado",
            "hemi-head",
            "hibernate",
            "highway-to-heck",
            "hollyweird",
            "hollywood",
            "hollywood-hills",
            "homeboy",
            "hominis",
            "honest-john",
            "hootie",
            "horny-devils",
            "horror-hotel",
            "hot-pizza",
            "hyundai",
            "i-suck-at-golf",
            "igloo-caps",
            "imprint",
            "incantation",
            "independence",
            "indochine",
            "inthacity",
            "intoxicated-blues",
            "intrepid",
            "invisible-killer",
            "iron-clad-bolted",
            "jazz-poster",
            "jeffrey-print",
            "jennifer-thin",
            "junegull",
            "jungle",
            "jungle-fever",
            "jungle-life",
            "kefka",
            "kick-assinger",
            "killer-boots",
            "kitchen-police",
            "kitty-katt",
            "knights-templar",
            "knuckle-down",
            "kosal-says-hy",
            "laconick",
            "laderbog",
            "lcd-mono-ultra",
            "legal-tender",
            "lemiesz",
            "lights-out",
            "loki-cola",
            "long-island",
            "lucida-handwriting",
            "mad-scientist",
            "madfont",
            "magnum",
            "manson-nights",
            "market",
            "marlboro",
            "meglaphoid",
            "miami-beach",
            "micro-N55",
            "micro-N56",
            "microgramma",
            "miltown-2",
            "mini",
            "minster",
            "misfit2",
            "mister-sinister",
            "mobile-infantry",
            "monotype-corsiva",
            "monsters-attack",
            "moonstar",
            "mr-goodbaur",
            "mummy-loves-you",
            "munster-bash",
            "my-puma",
            "national-first",
            "navy-blues",
            "netherworld",
            "neuropol",
            "never-say-die",
            "new-horizons",
            "nife-fite",
            "nife-fiter",
            "night-court",
            "night-sky",
            "nightmare",
            "nightsky",
            "niobium",
            "no-consequence",
            "nolo-contendre",
            "nose-bleed",
            "not-mary-kate",
            "note-scrawl",
            "nothing-in-between",
            "nougat",
            "ogilvie",
            "oh-my-god-stars",
            "oktoberfest",
            "olivers-barney",
            "one-8-seven",
            "one8seven",
            "orbus",
            "oreos",
            "overmuch",
            "pacmania",
            "painty-paint",
            "palatino",
            "papyrus",
            "parry-hotter",
            "penman",
            "pentagon",
            "perpetua",
            "phorfeit",
            "pickwick",
            "pirate",
            "pirate-keg",
            "plain-o-matic",
            "planet-benson-2",
            "plastique",
            "playtoy",
            "plump",
            "politician",
            "porkys",
            "pristina",
            "psychatronic",
            "psycho-poetry",
            "ptarmigan",
            "quill",
            "radonator-monster",
            "rage-italic",
            "ragged",
            "raiders",
            "reska-graf",
            "reticulum-3",
            "riggle",
            "rockwell",
            "rocky-horror",
            "rote-flora",
            "roughedge",
            "rugged-stencil",
            "sabrina",
            "sanguinary",
            "scarecrow",
            "schizm",
            "scythe",
            "seaweed-fire",
            "serpentine-bold",
            "shiver",
            "shlop",
            "shooting-star",
            "shopping-list",
            "shredded",
            "si-font",
            "sick-postman",
            "sideshow",
            "singothic",
            "skater-dudes",
            "skeleton-alphabet",
            "skinner",
            "skinny-cap-kick",
            "skrybylrr",
            "slammer-tag",
            "slayer-plain",
            "smash",
            "snickers",
            "snipple",
            "snow-caps",
            "snow-cups-caps",
            "snow-drift",
            "snow-dusted",
            "snowballs",
            "so-run-down",
            "sofachrome-italic",
            "soft-sugar-fade",
            "soft-sugar-plain",
            "solstice-of-suffering",
            "space-toaster",
            "spill-milk",
            "spirits",
            "sports-night",
            "star-caps",
            "star-dust",
            "star-font",
            "star-hound",
            "starbats",
            "stars-caps",
            "startone",
            "steamer",
            "stencil",
            "stencil-export",
            "stencil-four",
            "sthlm-graffiti",
            "styrofoam-feelings",
            "subway",
            "suvivant",
            "swamp-terror",
            "tags-extreme",
            "tags-xtreme",
            "tags-xtreme-2",
            "tagster",
            "technine",
            "technineclen",
            "the-guru-font",
            "the-sauce",
            "thug",
            "tie-wing",
            "tombstone",
            "tooth-ache",
            "trading-post",
            "trans-robotics",
            "transylvania",
            "trek-classic-credits",
            "tribal-funk",
            "trumania",
            "twentieth-century",
            "twinkle-star",
            "united-states",
            "urban",
            "urban-scrawl-buttah",
            "urban-scrawl-chill",
            "usuzi",
            "vampire",
            "vanish-in-the-heat",
            "verdana",
            "video-star",
            "viking-stencil",
            "violation",
            "vogue",
            "voodoo-doll",
            "vtc-lo-down",
            "walt-disney-script",
            "warlock",
            "weltron-urban",
            "west-side",
            "wild-ride",
            "wild-west-USA",
            "willy-wonka",
            "witchcraft",
            "writers-bold",
            "writers-condensed",
            "writers-original",
            "x-files",
            "yikes",
            "zenith",
            "zitcream",
            "zombie",
            "zombified",]

        return fonts[randrange(len(fonts))]

def main(argv):
    try: 
        (opts, args) = process_opts()
        spark_text = SparkleeText(**{'opts' : opts, 'args' : args})
        spark_text.run()
    except (EOFError, KeyboardInterrupt):
        print "\nCaught a cancel signal, exiting."
    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv))
